Alumno: **Ginés González Guirado**

# Homework 6

In [1]:
import numpy as np

6.1 We showed in class that the exact Fourier series for a square wave in "sine phase" (see Fig. 6.1) is equal to $$y(x) = \frac{4}{\pi} (sin(x) + \frac{1}{3}sin(3x) + \frac{1}{5}sin(5x) + ...) = \frac{4}{\pi} \sum_{k=odd} \frac{sin(kx)}{k}$$

Estimate the Fourier coefficients numerically by sampling this function at 8 points in the interval $(-\pi, \pi)$. Compare results with the exact answer given above. Repeat for 16 sample points.

Utilizo la función que definí en el homework anterior para obtener la matriz de cosenos y senos, y a partir de esto sacar los coeficientes de Fourier, ya que me dicen la cantidad de puntos que tengo que tomar y sé la forma de la función.

In [2]:
def ft(v,m):
    D=np.size(v)   # Dimension
    N=D//2         # Armonicos

    M=np.zeros((D,D))
    A=np.zeros((D,D))
    f=0    # la variable muda f, denota el orden de la columna que estamos rellenando
    for i in range(D):
        M[i,f]=1/np.sqrt(D)

    for k in range(1,N+1):
        f=f+1
        for i in range(D):
            M[i,f]=np.cos(2*k*np.pi*i/D)/np.sqrt(D/2)
        f=f+1 
        if f<=(D-1):  #si D es par, una vez llegado al último armónico, se llenará el vector de cosenos pero no el de senos
            for i in range(D):
                M[i,f]=np.sin(2*k*np.pi*i/D)/np.sqrt(D/2)
    #M será la matriz para la DFT inversa
    if(D%2==0):
        for i in range(D):
            M[i,D-1]=M[i,D-1]/np.sqrt(2)
    
    for i in range(D):
        for j in range(D):
            A[i,j]=M[j,i]  # la matriz para la DFT directa será la traspuesta
            
    if m==1:        
        f=np.sqrt(2/D)*np.dot(A,v) #si m=1 el resultado es la DFT directa
        return f
    elif m==-1:
        f=np.sqrt(D/2)*np.dot(M,v) #si m=-1 el resultado es la DFT inversa
        return f
    else:
        return print('entrada incorrecta: 1 directa, -1 inversa') #si m es disntinto de 1 o -1 ponemos un mensaje de error
    

Tomo un vector de 8 puntos de la función cuadrada que aparece en la (Fig. 6.1).

In [3]:
v=np.array([1,1,1,1,-1,-1,-1,-1])   # Vector de 8 puntos
np.round(ft(v,1),7)          # DFT directa y redondeo a la septima cifra decimal

array([0.       , 0.5      , 1.2071068, 0.       , 0.       , 0.5      ,
       0.2071068, 0.       ])

Calculo los coeficientes teóricos (fórmula 6.11 de los apuntes). Sólo calculo los coeficientes $b_k$, ya que los $a_k$ son nulos.

In [4]:
n=3     # calculo hasta b_3, ya que con 8 puntos solo podemos obtener numericamente hasta b_3
for i in range(1,n+1):
    if i%2==0:
        print(0)     # Coeficientes para i=par
    else:
        print(4/(i*np.pi))     # Coeficientes para i=impar

1.2732395447351628
0
0.4244131815783876


Se puede apreciar que si k es par, tanto $a_k$ como $b_k$ son 0, lo que coincide con los valores teóricos. Sin embargo, si k es impar, $a_k = 0.5$, el cual debería ser nulo, y de los $b_k$ el primero, $b_1$, es el más similar al valor teórico, el coeficiente $b_2$ es aproximadamente la mitad del valor teórico.

In [5]:
v=np.array([1,1,1,1,1,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1])      # Vector de 16 puntos
np.round(ft(v,1),7)          # DFT directa y redondeo a la septima cifra decimal

array([ 0.       ,  0.25     ,  1.2568349, -0.       ,  0.       ,
        0.25     ,  0.3741514,  0.       ,  0.       ,  0.25     ,
        0.1670447,  0.       , -0.       ,  0.25     ,  0.0497281,
        0.       ])

In [6]:
n=8      # Calculo hasta b_7
for i in range(1,n+1):
    if i%2==0:
        print(0)     # Coeficientes para i=par
    else:
        print(4/(i*np.pi))     # Coeficientes para i=impar

1.2732395447351628
0
0.4244131815783876
0
0.25464790894703254
0
0.18189136353359467
0


Como era de esperar, al aumentar los puntos se ha mejorado la precisión de los coeficientes, ahora los $a_k$ que antes eran 0.5 se han reducido a 0.25 , justo a la mitad y hemos doblado el número de puntos. Los coeficientes $b_k$ también se aproximan más a los teóricos. Los primeros coeficientes $b_k$ tienen menos error que conforme se va avanzando.

6.2 In the book "Visual Perception" by Tom Cornsweet, an intensity profile is shown in Fig. 14.3A that has the equation $$I(x) = 2 sin(x) - sin(2x)$$

Determine the Fourier coefficients for $I(x)$ numerically by sampling the function at 3 points. Repeat the analysis for 5 sample points. Repeat the analysis again for 7 points. Compare your results with the exact answer to determine how many sample points are required so that the numerical answer is exactly correct.

Defino la función.

In [7]:
def g(D):          # D son los puntos que voy a tomar
    g=np.zeros(D)  # Vector donde se almacenan los valores que tome la función
    for i in range(D):
        g[i]=2*np.sin(i*2*np.pi/D)-np.sin(i*4*np.pi/D)
    return g

In [8]:
g(3)    # Valores de la funcion si tomo 3 puntos

array([ 0.        ,  2.59807621, -2.59807621])

In [9]:
# Coeficientes de Fourier si tomo 3 puntos y redondeo a la septima cifra decimal
np.round(ft(g(3),1),7)

array([0., 0., 3.])

In [10]:
# Coeficientes de Fourier si tomo 5 puntos y redondeo a la septima cifra decimal
np.round(ft(g(5),1),7)

array([ 0., -0.,  2., -0., -1.])

In [11]:
# Coeficientes de Fourier si tomo 5 puntos y redondeo a la septima cifra decimal
np.round(ft(g(7),1),7)

array([-0.,  0.,  2., -0., -1., -0.,  0.])

Con 5 puntos ya se llega al resultado exacto. Aunque para comprobar que el resto de $b_k = 0$ cuando $k > 3$, no se puede con 5 puntos y el mínimo número de puntos para comprobar que se cumple esto es 7.